### ISSUE TITLE
Support THIS_IS_CONSTANT naming 

### ISSUE THREAD

**Issue by PinkyJie** [reesemclean/blueprint#59] opened 2018-10-24 01:54 UTC
This is a great library, thanks for your work!

Is it possible to support the constant naming style like THIS_IS_CONSTANT?

**Comment by reesemclean** [comment] 2018-11-10 01:39
Hey this looks a duplicate of #51 . I will close this one out and begin work on that issue. Thanks!

**Comment by reesemclean** [comment] 2018-11-10 01:39
Sure what would you call that transform?

**Comment by reesemclean** [comment] 2018-11-10 02:19
I have added it as {{upperSnakeCase name}}. It should be in the latest release. Thanks!

**Closed by reesemclean** 2018-11-10 02:19 UTC

**Comment by PinkyJie** [comment] 2018-11-10 03:29
@reesemclean thank you a lot for the fix, so responsive
